### ISSUE TITLE
Pipe data between assembler and emulator

### ISSUE THREAD

**Issue by geraintwhite** [itsapi/8-bit-emulator#2]
It would be very useful to run some assembly with `node assembler.js assembly | node main.js`.

**Comment by geraintwhite** [comment]
The output is piped correctly from assembler.js, but I cannot get main.js to receive a piped input correctly.

**Comment by geraintwhite** [comment]
Also, which should be prioritised:
- Assembler: `output file or pipe`
- Emulator:  `input file or pipe`

**Comment by geraintwhite** [comment]
dc1f06fa338a67239e146f0b82b914712fd90fe1

**Comment by olls** [comment]
Output file and input file should be prioritised over piping.

**Comment by geraintwhite** [comment]
That's how it is currently

**Comment by olls** [comment]
Good
